"""Baseline migration: create initial schema to match SQLAlchemy models.

This migration is intended as the first revision in the repository and should produce
no changes when running `alembic revision --autogenerate` against a DB migrated
to this revision.

Generated by hand to avoid destructive changes and to be deterministic across
SQLite (dev) and Postgres (Neon).
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enum types
    workflowstatus = sa.Enum("pending", "completed", "failed", name="workflowstatus")
    assettype = sa.Enum(
        "uploaded",
        "background_removed",
        "seedream",
        "final",
        name="assettype",
    )

    # Create enum types explicitly for Postgres
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        workflowstatus.create(bind, checkfirst=True)
        assettype.create(bind, checkfirst=True)

    # users
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "session_id", postgresql.UUID(as_uuid=True), nullable=False, unique=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_active", sa.DateTime(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("user_metadata", sa.JSON(), nullable=True),
    )

    # costumes
    op.create_table(
        "costumes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("reference_image_url", sa.Text(), nullable=False),
        sa.Column("affiliate_link", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    # workflow_runs
    op.create_table(
        "workflow_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_session", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column(
            "costume_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("costumes.id"),
            nullable=False,
        ),
        sa.Column("status", workflowstatus, nullable=False, server_default="pending"),
        sa.Column("uploaded_asset_url", sa.Text(), nullable=False),
        sa.Column("background_asset_url", sa.Text(), nullable=True),
        sa.Column("seedream_asset_url", sa.Text(), nullable=True),
        sa.Column("final_asset_url", sa.Text(), nullable=True),
        sa.Column("log_object_path", sa.Text(), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    # assets
    op.create_table(
        "assets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workflow_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workflow_runs.id"),
            nullable=False,
        ),
        sa.Column("asset_type", assettype, nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("public_url", sa.Text(), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    # processing_metrics
    op.create_table(
        "processing_metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workflow_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workflow_runs.id"),
            nullable=False,
        ),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True, server_default="0"),
    )

    # costume_popularity
    op.create_table(
        "costume_popularity",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "costume_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("costumes.id"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("success_count", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("average_processing_time", sa.Float(), nullable=True),
    )

    # workflow_preferences
    op.create_table(
        "workflow_preferences",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workflow_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workflow_runs.id"),
            nullable=False,
        ),
        sa.Column("selection_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    bind = op.get_bind()
    # Drop tables in reverse order
    op.drop_table("workflow_preferences")
    op.drop_table("costume_popularity")
    op.drop_table("processing_metrics")
    op.drop_table("assets")
    op.drop_table("workflow_runs")
    op.drop_table("costumes")
    op.drop_table("users")

    # Drop enum types for Postgres
    if bind.dialect.name == "postgresql":
        sa.Enum(name="assettype").drop(bind, checkfirst=True)
        sa.Enum(name="workflowstatus").drop(bind, checkfirst=True)
